# Generated by Django 6.0.4 on 2026-08-22 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=160, verbose_name="titulo")),
                ("descricao", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="responsavel"
                    ),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=120, verbose_name="area"),
                ),
                (
                    "origem",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="app ou origem"
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em andamento"),
                            ("concluida", "Concluida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "prazo",
                    models.DateField(blank=True, null=True, verbose_name="prazo"),
                ),
                ("follow_up", models.TextField(blank=True, verbose_name="follow-up")),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "tarefa de follow-up",
                "verbose_name_plural": "tarefas de follow-up",
                "ordering": ["status", "prazo", "-criado_em"],
            },
        ),
    ]
