# Generated by Django 6.0.4 on 2026-08-21 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Armario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="numero do armario"
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="nome do usuario"
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primeiro", "1 turno"),
                            ("segundo", "2 turno"),
                            ("terceiro", "3 turno"),
                            ("administrativo", "Administrativo"),
                            ("outro", "Outro"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "tamanho_camisa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pp", "PP"),
                            ("p", "P"),
                            ("m", "M"),
                            ("g", "G"),
                            ("gg", "GG"),
                            ("xg", "XG"),
                            ("xgg", "XGG"),
                            ("especial", "Especial"),
                        ],
                        max_length=16,
                        verbose_name="tamanho da camisa",
                    ),
                ),
                (
                    "tamanho_calca",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pp", "PP"),
                            ("p", "P"),
                            ("m", "M"),
                            ("g", "G"),
                            ("gg", "GG"),
                            ("xg", "XG"),
                            ("xgg", "XGG"),
                            ("especial", "Especial"),
                        ],
                        max_length=16,
                        verbose_name="tamanho da calca",
                    ),
                ),
                (
                    "tamanho_macacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pp", "PP"),
                            ("p", "P"),
                            ("m", "M"),
                            ("g", "G"),
                            ("gg", "GG"),
                            ("xg", "XG"),
                            ("xgg", "XGG"),
                            ("especial", "Especial"),
                        ],
                        max_length=16,
                        verbose_name="tamanho do macacao",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("livre", "Livre"),
                            ("ocupado", "Ocupado"),
                            ("manutencao", "Manutencao"),
                            ("inativo", "Inativo"),
                        ],
                        default="livre",
                        max_length=16,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "armario",
                "verbose_name_plural": "armarios",
                "ordering": ["numero"],
            },
        ),
    ]
