# Generated by Django 6.0.4 on 2026-08-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roupeiro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="armario",
            name="tamanho_calca_numero",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="tamanho numerico da calca"
            ),
        ),
        migrations.AddField(
            model_name="armario",
            name="tamanho_camisa_numero",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="tamanho numerico da camisa"
            ),
        ),
        migrations.AddField(
            model_name="armario",
            name="tamanho_macacao_numero",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="tamanho numerico do macacao"
            ),
        ),
    ]
