# Generated by Django 6.0.4 on 2026-08-22 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeadcountImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.DateField(verbose_name="mes de referencia")),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="headcount/%Y/%m/", verbose_name="arquivo headcount"
                    ),
                ),
                ("total_membros", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "importacao de headcount",
                "verbose_name_plural": "importacoes de headcount",
                "ordering": ["-mes", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="BirthdayList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.DateField(verbose_name="mes dos aniversariantes")),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="aniversariantes/%Y/%m/",
                        verbose_name="foto/lista de aniversariantes",
                    ),
                ),
                (
                    "texto_extraido",
                    models.TextField(
                        blank=True, verbose_name="texto extraido ou digitado da imagem"
                    ),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "headcount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_aniversariantes",
                        to="headcount.headcountimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "lista de aniversariantes",
                "verbose_name_plural": "listas de aniversariantes",
                "ordering": ["-mes", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="HeadcountMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=180)),
                ("nome_normalizado", models.CharField(db_index=True, max_length=180)),
                ("turno", models.CharField(blank=True, max_length=80)),
                (
                    "work_group",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="work group"
                    ),
                ),
                (
                    "team",
                    models.CharField(blank=True, max_length=140, verbose_name="team"),
                ),
                ("area", models.CharField(blank=True, max_length=180)),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="headcount.headcountimport",
                    ),
                ),
            ],
            options={
                "verbose_name": "membro do headcount",
                "verbose_name_plural": "membros do headcount",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="BirthdayName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=180)),
                ("nome_normalizado", models.CharField(db_index=True, max_length=180)),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomes",
                        to="headcount.birthdaylist",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="headcount.headcountmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "aniversariante",
                "verbose_name_plural": "aniversariantes",
                "ordering": ["nome"],
            },
        ),
    ]
