# Generated by Django 5.2.17 on 2026-08-21 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoZeladoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=120, verbose_name='nome do solicitante')),
                ('local', models.CharField(max_length=160, verbose_name='local')),
                ('descricao', models.TextField(verbose_name='descricao da necessidade')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='zeladoria/%Y/%m/', verbose_name='foto')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em analise'), ('ticket_aberto', 'Ticket aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='novo', max_length=20)),
                ('ticket_oficial', models.CharField(blank=True, max_length=80, verbose_name='ticket oficial')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes de follow-up')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'chamado de zeladoria',
                'verbose_name_plural': 'chamados de zeladoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
