# Generated by Django 5.2.17 on 2026-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeladoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadozeladoria',
            name='titulo',
            field=models.CharField(default='Chamado de zeladoria', max_length=140, verbose_name='titulo do chamado'),
        ),
    ]
