# Generated by Django 6.0.4 on 2026-08-22 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreinamentoSeguranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=160, verbose_name="titulo do treinamento"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("seguranca", "Seguranca"),
                            ("pintura", "Pintura"),
                            ("qualidade", "Qualidade"),
                            ("meio_ambiente", "Meio ambiente"),
                            ("outros", "Outros"),
                        ],
                        default="seguranca",
                        max_length=24,
                    ),
                ),
                ("data", models.DateField(verbose_name="data do treinamento")),
                ("empresa", models.CharField(max_length=140, verbose_name="empresa")),
                (
                    "area",
                    models.CharField(
                        default="Pintura", max_length=120, verbose_name="area"
                    ),
                ),
                (
                    "instrutor",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="instrutor"
                    ),
                ),
                (
                    "carga_horaria",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="carga horaria"
                    ),
                ),
                (
                    "validade",
                    models.DateField(blank=True, null=True, verbose_name="validade"),
                ),
                (
                    "documento",
                    models.FileField(
                        upload_to="treinamentos/", verbose_name="documento escaneado"
                    ),
                ),
                (
                    "texto_participantes",
                    models.TextField(
                        blank=True, verbose_name="texto dos participantes"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observacoes"),
                ),
                ("total_participantes", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "treinamento de seguranca",
                "verbose_name_plural": "treinamentos de seguranca",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ParticipanteTreinamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=160, verbose_name="nome")),
                (
                    "matricula",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="matricula"
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="empresa"
                    ),
                ),
                (
                    "turno",
                    models.CharField(blank=True, max_length=80, verbose_name="turno"),
                ),
                (
                    "area",
                    models.CharField(blank=True, max_length=120, verbose_name="area"),
                ),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "treinamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="treinamentos.treinamentoseguranca",
                    ),
                ),
            ],
            options={
                "verbose_name": "participante de treinamento",
                "verbose_name_plural": "participantes de treinamento",
                "ordering": ["nome"],
            },
        ),
    ]
