# Generated by Django 6.0.4 on 2026-08-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treinamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinamentoseguranca",
            name="hora_fim",
            field=models.TimeField(
                blank=True, null=True, verbose_name="hora de termino"
            ),
        ),
        migrations.AddField(
            model_name="treinamentoseguranca",
            name="hora_inicio",
            field=models.TimeField(
                blank=True, null=True, verbose_name="hora de inicio"
            ),
        ),
        migrations.AddField(
            model_name="treinamentoseguranca",
            name="status",
            field=models.CharField(
                choices=[
                    ("agendado", "Agendado"),
                    ("realizado", "Realizado"),
                    ("cancelado", "Cancelado"),
                ],
                default="agendado",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="treinamentoseguranca",
            name="documento",
            field=models.FileField(
                blank=True,
                upload_to="treinamentos/",
                verbose_name="documento escaneado",
            ),
        ),
    ]
