# Generated by Django 6.0.4 on 2026-08-21 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10, verbose_name="metodo")),
                (
                    "path",
                    models.CharField(max_length=500, verbose_name="rota acessada"),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(verbose_name="codigo de resposta"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="endereco IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="navegador/dispositivo"),
                ),
                (
                    "referer",
                    models.CharField(blank=True, max_length=500, verbose_name="origem"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data do acesso"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "acesso",
                "verbose_name_plural": "metricas de acesso",
                "ordering": ["-created_at"],
            },
        ),
    ]
