# Generated by Django 5.2.17 on 2026-08-21 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='titulo do chamado')),
                ('solicitante', models.CharField(max_length=120, verbose_name='nome do solicitante')),
                ('setor', models.CharField(blank=True, max_length=120, verbose_name='setor ou area')),
                ('categoria', models.CharField(choices=[('conta', 'Abertura ou acesso de conta'), ('equipamento', 'Equipamento'), ('sistema', 'Sistema'), ('rede', 'Rede'), ('email', 'E-mail'), ('outros', 'Outros')], default='outros', max_length=24)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=16)),
                ('descricao', models.TextField(verbose_name='descricao do membro')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em analise'), ('em_andamento', 'Em andamento'), ('aguardando_terceiros', 'Aguardando terceiros'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='novo', max_length=28)),
                ('ticket_oficial', models.CharField(blank=True, max_length=80, verbose_name='ticket oficial')),
                ('solucao', models.TextField(blank=True, verbose_name='solucao ou follow-up')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'chamado de TI',
                'verbose_name_plural': 'chamados de TI',
                'ordering': ['-criado_em'],
            },
        ),
    ]
